services:
  workspace:
    container_name: nestjs_devcon_workspace
    image: mcr.microsoft.com/devcontainers/base:bullseye
    command: sleep infinity
    volumes:
      # Workspace Cache
      - ..:${containerWorkspaceFolder}:cached